---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 274292674-q5emfaX95X1Ayjfiw5alTwMofxfU45Js3kcem4aG
:access_token_secret: 9QLIA36INpGKK8IUpbMB6vv92clC9fqLbw7HxEP4jIaFN
